start_gui
create_project scrambler ./scrambler -part xc7z020clg484-1
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property target_language VHDL [current_project]
create_peripheral user.org user scrambler_axi_ip 1.0 -dir ./ip_repo
add_peripheral_interface S00_AXI -interface_mode slave -axi_type lite [ipx::find_open_core user.org:user:scrambler_axi_ip:1.0]
generate_peripheral -driver -bfm_example_design -debug_hw_example_design -force [ipx::find_open_core user.org:user:scrambler_axi_ip:1.0]
write_peripheral [ipx::find_open_core user.org:user:scrambler_axi_ip:1.0]
set_property  ip_repo_paths  ./ip_repo/scrambler_axi_ip_1.0 [current_project]
update_ip_catalog -rebuild
ipx::edit_ip_in_project -upgrade true -name edit_scrambler_axi_ip_v1_0 -directory ./ip_repo ./ip_repo/scrambler_axi_ip_1.0/component.xml
update_compile_order -fileset sources_1
add_files -norecurse -copy_to ./ip_repo/scrambler_axi_ip_1.0/src {./RTL/scrambler.vhd ./RTL/bram.vhd}
update_files -from_files ./RTL/scrambler_axi_ip_v1_0.vhd -to_files ./ip_repo/scrambler_axi_ip_1.0/hdl/scrambler_axi_ip_v1_0.vhd -filesets [get_filesets *]
update_files -from_files ./RTL/scrambler_axi_ip_v1_0_S00_AXI.vhd -to_files ./ip_repo/scrambler_axi_ip_1.0/hdl/scrambler_axi_ip_v1_0_S00_AXI.vhd -filesets [get_filesets *]
update_compile_order -fileset sources_1
set_property SOURCE_SET sources_1 [get_filesets sim_1]
add_files -fileset sim_1 -norecurse -copy_to ./ip_repo/scrambler_axi_ip_1.0/src ./Testbench/scrambler_tb.vhd
update_compile_order -fileset sim_1
update_compile_order -fileset sim_1
set_property library work [get_files  ./ip_repo/scrambler_axi_ip_1.0/src/scrambler.vhd]
set_property library work [get_files  ./ip_repo/scrambler_axi_ip_1.0/src/bram.vhd]
set_property library work [get_files  ./RTL/scrambler_axi_ip_v1_0_S00_AXI.vhd]
set_property library work [get_files  ./RTL/scrambler_axi_ip_v1_0.vhd]
set_property library work [get_files  ./ip_repo/scrambler_axi_ip_1.0/src/scrambler_tb.vhd]
launch_runs synth_1
ipx::merge_project_changes ports [ipx::current_core]
update_compile_order -fileset sources_1
ipx::add_bus_interface bramA [ipx::current_core]
set_property abstraction_type_vlnv xilinx.com:interface:bram_rtl:1.0 [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property bus_type_vlnv xilinx.com:interface:bram:1.0 [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property display_name bramA [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property description bramA [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
ipx::add_port_map RST [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property physical_name reseta [ipx::get_port_maps RST -of_objects [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]]
ipx::add_port_map CLK [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property physical_name clka [ipx::get_port_maps CLK -of_objects [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]]
ipx::add_port_map DIN [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property physical_name dina [ipx::get_port_maps DIN -of_objects [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]]
ipx::add_port_map EN [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property physical_name ena [ipx::get_port_maps EN -of_objects [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]]
ipx::add_port_map DOUT [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property physical_name douta [ipx::get_port_maps DOUT -of_objects [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]]
ipx::add_port_map WE [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property physical_name wea [ipx::get_port_maps WE -of_objects [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]]
ipx::add_port_map ADDR [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property physical_name addra [ipx::get_port_maps ADDR -of_objects [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]]
ipx::add_bus_parameter MEM_SIZE [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
ipx::add_bus_parameter MEM_WIDTH [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
ipx::add_bus_interface bramB [ipx::current_core]
set_property abstraction_type_vlnv xilinx.com:interface:bram_rtl:1.0 [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property bus_type_vlnv xilinx.com:interface:bram:1.0 [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property display_name bramB [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property description bramB [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
ipx::add_port_map RST [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property physical_name resetb [ipx::get_port_maps RST -of_objects [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]]
ipx::add_port_map CLK [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property physical_name clkb [ipx::get_port_maps CLK -of_objects [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]]
ipx::add_port_map DIN [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property physical_name dinb [ipx::get_port_maps DIN -of_objects [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]]
ipx::add_port_map EN [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property physical_name enb [ipx::get_port_maps EN -of_objects [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]]
ipx::add_port_map DOUT [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property physical_name doutb [ipx::get_port_maps DOUT -of_objects [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]]
ipx::add_port_map WE [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property physical_name web [ipx::get_port_maps WE -of_objects [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]]
ipx::add_port_map ADDR [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
set_property physical_name addrb [ipx::get_port_maps ADDR -of_objects [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]]
ipx::add_bus_parameter MEM_SIZE [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
ipx::add_bus_parameter MEM_WIDTH [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
ipx::remove_bus_parameter MEM_WIDTH [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
ipx::add_bus_parameter x [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
ipx::remove_bus_parameter x [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
ipx::add_bus_parameter CONFIG.MASTER_TYPE [ipx::get_bus_interfaces bramB -of_objects [ipx::current_core]]
ipx::remove_bus_parameter MEM_WIDTH [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
ipx::add_bus_parameter CONFIG.MASTER_TYPE [ipx::get_bus_interfaces bramA -of_objects [ipx::current_core]]
set_property core_revision 2 [ipx::current_core]
ipx::update_source_project_archive -component [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::save_core [ipx::current_core]
ipx::move_temp_component_back -component [ipx::current_core]
close_project -delete
update_ip_catalog -rebuild -repo_path ./ip_repo/scrambler_axi_ip_1.0
